spring.application.name=project_sphere
server.port=8082

#Database Connection Settings

spring.datasource.url=jdbc:mysql://localhost:3306/projectsphere?useSSL=false&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=Mysql@1234
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver


#Hibernate & JPA Properties

#spring.jpa.hibernate.ddl-auto=update
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.sql.init.mode=always
# Tell Spring to defer data initialization until after JPA/Hibernate is ready
spring.jpa.defer-datasource-initialization=true

#Springboot Default HikariCP Configuration

#??????????????????????????????